print("##########")
print("#        #")
print("#        #")
print("##########")
print()
eye = input("Please enter a character for the eye")
print("Beep's expression is now as follows:")
print("##########")
print(f"#  {eye}  {eye}  #")
print("# ______ #")
print("##########")
