#Beep is getting better
print("Please enter the number of lives.")
lives = int(input())
print("Please enter the energy level.")
energy = int(input())
print("Please enter the shield level.")
shield = int(input())
print()
print()
print("Health has been set.")
print()
print()
print(f"Lives: {'￭' * lives}")
print(f"Energy: {'￭' * energy}")
print(f"Shield: {'￭' * shield}")